# Generated by Django 2.0.2 on 2018-03-05 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumin',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='issuein',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
