# Generated by Django 2.0.2 on 2018-04-27 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20180326_1823'),
        ('webapp', '0004_auto_20180427_1309'),
    ]

    operations = [
    ]
